name: Deploy
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  deploy:
    name: Deploy the project
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: composer install
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "/var/www/vhosts/often-test/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
      - name: Migrate Database
        run: vendor/bin/doctrine-migrations migrate
