name: Deploy
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  deploy:
    name: Deploy the project
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/vhosts/often-test/"
          SOURCE: "./"
